Test7 (#27)
* Initial commit.

diff --git a/.github/workflows/common.yml b/.github/workflows/common.yml
--- a/.github/workflows/common.yml
+++ b/.github/workflows/common.yml
@@ -1,203 +1,203 @@
-name: Common
-
-on:
-  push:
-    branches:
-      - test
-    tags:
-      - v[0-9]+.[0-9]+.[0-9]+*
-
-  pull_request:
-
-  workflow_call:
-    inputs:
-      go-version:
-        description: An array of Go versions to be tested against, in a format of json string.
-        required: false
-        type: string
-        default: '["tip"]'
-
-
-jobs:
-  check:
-    name: Checks
-    runs-on: ubuntu-22.04
-    strategy:
-      fail-fast: false
-      matrix:
-        go-version: ${{ fromJson(inputs.go-version || '["1.18.x"]') }}
-
-    env:
-      GO_VERSION: ${{ matrix.go-version }}
-      GOPATH: ${{ github.workspace }}
-      WORKING_DIR: ${{ github.workspace }}/src/github.com/percona/pmm
-
-    defaults:
-      run:
-        working-directory: ${{ env.WORKING_DIR }}
-
-    steps:
-
-      - name: Check out code into the working directory under the GOPATH
-        uses: percona-platform/checkout@v3
-        with:
-          fetch-depth: 1
-          path: ${{ env.WORKING_DIR }}
-
-      - name: Set up Go release
-        if: env.GO_VERSION != 'tip'
-        uses: percona-platform/setup-go@v2
-        with:
-          go-version: ${{ env.GO_VERSION }}
-
-      - name: Set up Go tip
-        if: env.GO_VERSION == 'tip'
-        run: |
-          git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
-          cd $HOME/gotip/src
-          ./make.bash
-          echo "GOROOT=$HOME/gotip" >> $GITHUB_ENV
-          echo "$HOME/gotip/bin" >> $GITHUB_PATH
-
-      - name: Enable Go modules cache
-        uses: percona-platform/cache@v2
-        with:
-          path: ~/go/pkg/mod
-          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-modules-${{ hashFiles('**/go.sum') }}
-          restore-keys: |
-            ${{ runner.os }}-go-${{ env.GO_VERSION }}-modules-
-
-      - name: Download Go modules
-        run: go mod download
-
-      - name: Install development tools
-        run: make init
-
-      - name: Check build
-        run: make release
-
-#      - name: Run check-license
-#        run: |
-#          # go run ../.github/check-license.go # TODO: This repo has multiple licenses, fix checker. https://jira.percona.com/browse/PMM-10118
+#name: Common
 #
-#      - name: Run go-sumtype
-#        run: bin/go-sumtype ./...
-
-      - name: Run golangci-lint
-        env:
-          COMMAND: "bin/golangci-lint run -c=.golangci-required.yml --out-format=line-number"
-          REDIRECT: "| bin/reviewdog -f=golangci-lint -reporter=github-pr-review -fail-on-error=true"
-          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.ROBOT_TOKEN || secrets.GITHUB_TOKEN }}
-        run: |
-          if out=$( ${{ env.COMMAND }} ); exit_code=$?; [ $exit_code -ne 0 ]; then
-            echo Here1
-            if [ $exit_code -gt 1 ] || ${{ github.event.pull_request == null }}; then
-              echo Here2
-              echo "$out"
-              exit $exit_code
-            else
-              echo Here3
-              echo "$out" ${{ env.REDIRECT }}
-            fi
-          else
-            echo Here4
-            echo "$out"
-          fi
-
-
-#      - name: Run go-consistent
+#on:
+#  push:
+#    branches:
+#      - test
+#    tags:
+#      - v[0-9]+.[0-9]+.[0-9]+*
+#
+#  pull_request:
+#
+#  workflow_call:
+#    inputs:
+#      go-version:
+#        description: An array of Go versions to be tested against, in a format of json string.
+#        required: false
+#        type: string
+#        default: '["tip"]'
+#
+#
+#jobs:
+#  check:
+#    name: Checks
+#    runs-on: ubuntu-22.04
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        go-version: ${{ fromJson(inputs.go-version || '["1.18.x"]') }}
+#
+#    env:
+#      GO_VERSION: ${{ matrix.go-version }}
+#      GOPATH: ${{ github.workspace }}
+#      WORKING_DIR: ${{ github.workspace }}/src/github.com/percona/pmm
+#
+#    defaults:
+#      run:
+#        working-directory: ${{ env.WORKING_DIR }}
+#
+#    steps:
+#
+#      - name: Check out code into the working directory under the GOPATH
+#        uses: percona-platform/checkout@v3
+#        with:
+#          fetch-depth: 1
+#          path: ${{ env.WORKING_DIR }}
+#
+#      - name: Set up Go release
+#        if: env.GO_VERSION != 'tip'
+#        uses: percona-platform/setup-go@v2
+#        with:
+#          go-version: ${{ env.GO_VERSION }}
+#
+#      - name: Set up Go tip
+#        if: env.GO_VERSION == 'tip'
+#        run: |
+#          git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
+#          cd $HOME/gotip/src
+#          ./make.bash
+#          echo "GOROOT=$HOME/gotip" >> $GITHUB_ENV
+#          echo "$HOME/gotip/bin" >> $GITHUB_PATH
+#
+#      - name: Enable Go modules cache
+#        uses: percona-platform/cache@v2
+#        with:
+#          path: ~/go/pkg/mod
+#          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-modules-${{ hashFiles('**/go.sum') }}
+#          restore-keys: |
+#            ${{ runner.os }}-go-${{ env.GO_VERSION }}-modules-
+#
+#      - name: Download Go modules
+#        run: go mod download
+#
+#      - name: Install development tools
+#        run: make init
+#
+#      - name: Check build
+#        run: make release
+#
+##      - name: Run check-license
+##        run: |
+##          # go run ../.github/check-license.go # TODO: This repo has multiple licenses, fix checker. https://jira.percona.com/browse/PMM-10118
+##
+##      - name: Run go-sumtype
+##        run: bin/go-sumtype ./...
+#
+#      - name: Run golangci-lint
 #        env:
-#          COMMAND: 'bin/go-consistent -pedantic -exclude "tests" ./...'
-#          REDIRECT: "| bin/reviewdog -f=go-consistent -reporter=github-pr-review -fail-on-error=true"
+#          COMMAND: "bin/golangci-lint run -c=.golangci-required.yml --out-format=line-number"
+#          REDIRECT: "| bin/reviewdog -f=golangci-lint -reporter=github-pr-review -fail-on-error=true"
 #          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.ROBOT_TOKEN || secrets.GITHUB_TOKEN }}
 #        run: |
 #          if out=$( ${{ env.COMMAND }} ); exit_code=$?; [ $exit_code -ne 0 ]; then
-#            exit_code=$?
+#            echo Here1
 #            if [ $exit_code -gt 1 ] || ${{ github.event.pull_request == null }}; then
+#              echo Here2
 #              echo "$out"
 #              exit $exit_code
 #            else
+#              echo Here3
 #              echo "$out" ${{ env.REDIRECT }}
 #            fi
 #          else
+#            echo Here4
 #            echo "$out"
 #          fi
 #
-#      - name: Run optional checks/linters
-#        env:
-#          COMMAND: "bin/golangci-lint run --out-format=line-number"
-#          REDIRECT: "| bin/reviewdog -f=golangci-lint -reporter=github-pr-review"
-#          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.ROBOT_TOKEN || secrets.GITHUB_TOKEN }}
+#
+##      - name: Run go-consistent
+##        env:
+##          COMMAND: 'bin/go-consistent -pedantic -exclude "tests" ./...'
+##          REDIRECT: "| bin/reviewdog -f=go-consistent -reporter=github-pr-review -fail-on-error=true"
+##          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.ROBOT_TOKEN || secrets.GITHUB_TOKEN }}
+##        run: |
+##          if out=$( ${{ env.COMMAND }} ); exit_code=$?; [ $exit_code -ne 0 ]; then
+##            exit_code=$?
+##            if [ $exit_code -gt 1 ] || ${{ github.event.pull_request == null }}; then
+##              echo "$out"
+##              exit $exit_code
+##            else
+##              echo "$out" ${{ env.REDIRECT }}
+##            fi
+##          else
+##            echo "$out"
+##          fi
+##
+##      - name: Run optional checks/linters
+##        env:
+##          COMMAND: "bin/golangci-lint run --out-format=line-number"
+##          REDIRECT: "| bin/reviewdog -f=golangci-lint -reporter=github-pr-review"
+##          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.ROBOT_TOKEN || secrets.GITHUB_TOKEN }}
+##        run: |
+##          if ! out=$( ${{ env.COMMAND }} ); then
+##            exit_code=$?
+##            if [ $exit_code -gt 1 ] || ${{ github.event.pull_request == null }}; then
+##              echo "$out"
+##              exit $exit_code
+##            else
+##              echo "$out" ${{ env.REDIRECT }}
+##            fi
+##          else
+##            echo "$out"
+##          fi
+#
+#      - name: Test common API
+#        run: make test-common
+#
+#      - name: Run debug commands on failure
+#        if: ${{ failure() }}
 #        run: |
-#          if ! out=$( ${{ env.COMMAND }} ); then
-#            exit_code=$?
-#            if [ $exit_code -gt 1 ] || ${{ github.event.pull_request == null }}; then
-#              echo "$out"
-#              exit $exit_code
-#            else
-#              echo "$out" ${{ env.REDIRECT }}
-#            fi
-#          else
-#            echo "$out"
-#          fi
-
-      - name: Test common API
-        run: make test-common
-
-      - name: Run debug commands on failure
-        if: ${{ failure() }}
-        run: |
-          go version
-
-  merge-gatekeeper:
-    needs: [check]
-    if: ${{ always() }}
-    runs-on: ubuntu-22.04
-    steps:
-      - name: Run Merge Gatekeeper
-        uses: percona-platform/merge-gatekeeper@v1.0.2
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          interval: 45
-          timeout: 1200
-          ref: ${{ github.event.pull_request.head.sha || github.sha }}
-
-  workflow_success:
-    needs: [merge-gatekeeper]
-    name: Slack Notification success
-    runs-on: ubuntu-22.04
-    env:
-      SLACK_WEBHOOK: ${{ secrets.SLACK_TOKEN_PMM_CI }}
-      SLACK_CHANNEL: "pmm-ci"
-      SLACK_USERNAME: "PR pipelines bot"
-      SLACK_ICON_EMOJI: ":chestnut:"
-      SLACK_COLOR: "#00FF00"
-      SLACK_TITLE: "Finished ${{ github.event.repository.name }} workflow"
-      SLACK_MESSAGE: "${{ github.event.inputs.repo || github.repository }}:${{ github.event.inputs.branch || github.head_ref }}"
-
-    steps:
-#      - uses: percona-platform/checkout@v3
-#      - uses: percona-platform/setup-node@v2
-      - name: Slack Notification
-        run: echo Success
-#        uses: percona-platform/action-slack-notify@v2
-
-  workflow_failure:
-    if: ${{ failure() }}
-    needs: [merge-gatekeeper]
-    name: Slack Notification failure
-    runs-on: ubuntu-22.04
-    env:
-      SLACK_WEBHOOK: ${{ secrets.SLACK_TOKEN_PMM_CI }}
-      SLACK_CHANNEL: "pmm-ci"
-      SLACK_USERNAME: "PR pipelines bot"
-      SLACK_ICON_EMOJI: ":chestnut:"
-      SLACK_COLOR: "#FF0000"
-      SLACK_TITLE: "Finished ${{ github.event.repository.name }} workflow"
-      SLACK_MESSAGE: "Workflow failed: ${{ github.event.inputs.repo || github.repository }}:${{ github.event.inputs.branch || github.head_ref }}"
-
-    steps:
-#      - uses: percona-platform/checkout@v3
-      - name: Slack Notification
-        run: echo Failure
-#        uses: percona-platform/action-slack-notify@v2
+#          go version
+#
+#  merge-gatekeeper:
+#    needs: [check]
+#    if: ${{ always() }}
+#    runs-on: ubuntu-22.04
+#    steps:
+#      - name: Run Merge Gatekeeper
+#        uses: percona-platform/merge-gatekeeper@v1.0.2
+#        with:
+#          token: ${{ secrets.GITHUB_TOKEN }}
+#          interval: 45
+#          timeout: 1200
+#          ref: ${{ github.event.pull_request.head.sha || github.sha }}
+#
+#  workflow_success:
+#    needs: [merge-gatekeeper]
+#    name: Slack Notification success
+#    runs-on: ubuntu-22.04
+#    env:
+#      SLACK_WEBHOOK: ${{ secrets.SLACK_TOKEN_PMM_CI }}
+#      SLACK_CHANNEL: "pmm-ci"
+#      SLACK_USERNAME: "PR pipelines bot"
+#      SLACK_ICON_EMOJI: ":chestnut:"
+#      SLACK_COLOR: "#00FF00"
+#      SLACK_TITLE: "Finished ${{ github.event.repository.name }} workflow"
+#      SLACK_MESSAGE: "${{ github.event.inputs.repo || github.repository }}:${{ github.event.inputs.branch || github.head_ref }}"
+#
+#    steps:
+##      - uses: percona-platform/checkout@v3
+##      - uses: percona-platform/setup-node@v2
+#      - name: Slack Notification
+#        run: echo Success
+##        uses: percona-platform/action-slack-notify@v2
+#
+#  workflow_failure:
+#    if: ${{ failure() }}
+#    needs: [merge-gatekeeper]
+#    name: Slack Notification failure
+#    runs-on: ubuntu-22.04
+#    env:
+#      SLACK_WEBHOOK: ${{ secrets.SLACK_TOKEN_PMM_CI }}
+#      SLACK_CHANNEL: "pmm-ci"
+#      SLACK_USERNAME: "PR pipelines bot"
+#      SLACK_ICON_EMOJI: ":chestnut:"
+#      SLACK_COLOR: "#FF0000"
+#      SLACK_TITLE: "Finished ${{ github.event.repository.name }} workflow"
+#      SLACK_MESSAGE: "Workflow failed: ${{ github.event.inputs.repo || github.repository }}:${{ github.event.inputs.branch || github.head_ref }}"
+#
+#    steps:
+##      - uses: percona-platform/checkout@v3
+#      - name: Slack Notification
+#        run: echo Failure
+##        uses: percona-platform/action-slack-notify@v2
